exclude: ^.*\b(migrations|docker|grafana-dashboard.json)\b.*$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: pretty-format-json
        args: [
          --autofix,
          "--indent", "4",
        ]
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [
          --branch, develop,
        ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [ --py312-plus ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
      name: isort (python)


#  - repo: local
#    hooks:
#      - id: mypy
#        name: Run mypy via make
#        entry: make mypy
#        language: system
#        types: [ python ]